Standardized styles
Mostly updates to whitespace and some basic formatting.

diff --git a/bin/ms_tmp-cleaner b/bin/ms_tmp-cleaner
--- a/bin/ms_tmp-cleaner
+++ b/bin/ms_tmp-cleaner
@@ -24,51 +24,48 @@
 #
 #   Options:
 #
-#   -h,	Display help.
-#   -o,	Filter file older than X days; default 7
+#   -h,  Display help.
+#   -o,  Filter file older than X days; default 7
 #
-
 
 PROGNAME='ms_tmp-cleaner'
 VERSION='1.0'
 
 usage() {
-  cat <<- _EOF_
+  cat <<-_EOF_
   Usage: $PROGNAME [-h] -o '7'
 
   Options:
 
-  -h,	Display help.
-  -o,	Filter file older than X days; default 7
+  -h,  Display help.
+  -o,  Filter file older than X days; default 7
 
 _EOF_
 }
 
-while getopts ":ho:" option
-do
+while getopts ":ho:" option; do
   case $option in
-    h)
-	usage
-	exit 0
-	;;
-    o)
-	olderthan=$OPTARG
-	;;
-    :)
-	echo "option $OPTARG requires an argument"
-	exit 1
-	;;
-    ?)
-	echo "$OPTARG : invalid option"
-	exit 1
-	;;
+  h)
+    usage
+    exit 0
+    ;;
+  o)
+    olderthan=$OPTARG
+    ;;
+  :)
+    echo "option $OPTARG requires an argument"
+    exit 1
+    ;;
+  ?)
+    echo "$OPTARG : invalid option"
+    exit 1
+    ;;
   esac
 done
 
-if [ "$olderthan" == '' ]
-  then
-    olderthan=7
-    exit 1
+if [ "$olderthan" == '' ]; then
+  olderthan=7
+  exit 1
 fi
 
 find /var/spamtagger/spool/tmp/mailscanner -maxdepth 1 -mmin +$olderthan -name msg-* -print -exec rm -rf {} \;
